import schemas from '../../../schemas/old/index.js';
import * as routers from '../../../middleware/routeMiddleware.js';
import * as testData from '../../../../tests/testData.js';
import { EXTERNAL_URL } from '../../index.js';

import { createResourceAndItemIdLookup } from '../../../utils/specialLookups.js';

const oldEventDataTypes = {
	'patches-healths': {
		externalUrl: `${EXTERNAL_URL}patches-healths/`,
		schema: schemas.patchHealthSchema,
		newTypes: ['patch-health-records'],
		testData: [testData.patchHealth],
		lookupFields: [
			{
				fieldName: 'world_id',
				newFieldName: 'world_id',
				table: 'worlds',
				externalIdField: 'fv_world_id',
				internalIdField: 'world_id',
				requiresWorldId: false,
			},
			{
				fieldName: 'patch_id',
				newFieldName: 'patch_id',
				table: 'patches',
				externalIdField: 'fv_patch_id',
				internalIdField: 'patch_id',
				requiresWorldId: false,
			},
			{
				fieldName: 'game_time_id',
				newFieldName: 'game_time_id',
				table: 'game_times',
				externalIdField: 'fv_game_time_id',
				internalIdField: 'game_time_id',
				requiresWorldId: false,
			},
		],
	},
	'patches-events': {
		externalUrl: `${EXTERNAL_URL}patches-events/`,
		schema: schemas.patchEventSchema,
		router: routers.routePatchEvents,
		newTypes: ['patch-actions', 'patch-tending-actions'],
		testData: [testData.patchEvent1, testData.patchEvent2],
		lookupFields: [
			{
				fieldName: 'world_id',
				newFieldName: 'world_id',
				table: 'worlds',
				externalIdField: 'fv_world_id',
				internalIdField: 'world_id',
				requiresWorldId: false,
			},
			{
				fieldName: 'player_id',
				newFieldName: 'player_id',
				table: 'players',
				externalIdField: 'fv_player_id',
				internalIdField: 'player_id',
				requiresWorldId: false,
			},
			{
				fieldName: 'patch_id',
				newFieldName: 'patch_id',
				table: 'patches',
				externalIdField: 'fv_patch_id',
				internalIdField: 'patch_id',
				requiresWorldId: false,
			},
			{
				fieldName: 'game_time_id',
				newFieldName: 'game_time_id',
				table: 'game_times',
				externalIdField: 'fv_game_time_id',
				internalIdField: 'game_time_id',
				requiresWorldId: false,
			},
			{
				fieldName: 'item_id',
				newFieldName: 'item_id',
				table: 'items',
				externalIdField: 'fv_item_id',
				internalIdField: 'item_id',
				requiresWorldId: true,
			},
			{
				fieldName: 'creature_id',
				newFieldName: 'creature_id',
				table: 'creatures',
				externalIdField: 'fv_creature_id',
				internalIdField: 'creature_id',
				requiresWorldId: false,
			},
		],
	},
	'personal-reputations': {
		externalUrl: `${EXTERNAL_URL}personal-reputations/`,
		schema: schemas.personalReputationSchema,
		newTypes: ['friendship-records'],
		testData: [testData.personalReputation],
		lookupFields: [
			{
				fieldName: 'world_id',
				newFieldName: 'world_id',
				table: 'worlds',
				externalIdField: 'fv_world_id',
				internalIdField: 'world_id',
				requiresWorldId: false,
			},
			{
				fieldName: 'player_id',
				newFieldName: 'player_id',
				table: 'players',
				externalIdField: 'fv_player_id',
				internalIdField: 'player_id',
				requiresWorldId: false,
			},
			{
				fieldName: 'creature_id',
				newFieldName: 'creature_id',
				table: 'creatures',
				externalIdField: 'fv_creature_id',
				internalIdField: 'creature_id',
				requiresWorldId: false,
			},
			{
				fieldName: 'game_time_id',
				newFieldName: 'game_time_id',
				table: 'game_times',
				externalIdField: 'fv_game_time_id',
				internalIdField: 'game_time_id',
				requiresWorldId: false,
			},
		],
	},
	'weather-events': {
		externalUrl: `${EXTERNAL_URL}weather-events/`,
		schema: schemas.weatherEventSchema,
		newTypes: ['weather-records'],
		testData: [testData.weatherEvent],
		lookupFields: [
			{
				fieldName: 'world_id',
				newFieldName: 'world_id',
				table: 'worlds',
				externalIdField: 'fv_world_id',
				internalIdField: 'world_id',
				requiresWorldId: false,
			},
			{
				fieldName: 'day_id',
				newFieldName: 'day_id',
				table: 'days',
				externalIdField: 'fv_day_id',
				internalIdField: 'day_id',
				requiresWorldId: false,
			},
			{
				fieldName: 'weather_event_island',
				newFieldName: 'island_id',
				table: 'islands',
				externalIdField: 'fv_island_id',
				internalIdField: 'island_id',
				requiresWorldId: false,
			},
		],
	},
	'interaction-events': {
		externalUrl: `${EXTERNAL_URL}interaction-events/`,
		schema: schemas.interactionEventSchema,
		router: routers.routeInteractionEvents,
		newTypes: ['foraging-actions', 'crafting-actions', 'giving-actions'],
		testData: [
			testData.interactionEvent1,
			testData.interactionEvent2,
			testData.interactionEvent3,
		],
		lookupFields: [
			{
				fieldName: 'world_id',
				newFieldName: 'world_id',
				table: 'worlds',
				externalIdField: 'fv_world_id',
				internalIdField: 'world_id',
				requiresWorldId: false,
			},
			{
				fieldName: 'player_id',
				newFieldName: 'player_id',
				table: 'players',
				externalIdField: 'fv_player_id',
				internalIdField: 'player_id',
				requiresWorldId: false,
			},
			{
				fieldName: 'creature_id',
				newFieldName: 'creature_id',
				table: 'creatures',
				externalIdField: 'fv_creature_id',
				internalIdField: 'creature_id',
				requiresWorldId: false,
			},
			{
				fieldName: 'game_time_id',
				newFieldName: 'game_time_id',
				table: 'game_times',
				externalIdField: 'fv_game_time_id',
				internalIdField: 'game_time_id',
				requiresWorldId: false,
			},
			{
				fieldName: 'location_id',
				newFieldName: 'area_id',
				table: 'areas',
				externalIdField: 'fv_area_id',
				internalIdField: 'area_id',
				requiresWorldId: false,
			},
			{
				fieldName: 'patch_id',
				newFieldName: 'patch_id',
				table: 'patches',
				externalIdField: 'fv_patch_id',
				internalIdField: 'patch_id',
				requiresWorldId: false,
			},
		],
		specialLookups: [createResourceAndItemIdLookup],
	},
	'creature-move-events': {
		externalUrl: `${EXTERNAL_URL}creature-move-events/`,
		schema: schemas.creatureMoveEventSchema,
		newTypes: ['creature-state-records'],
		testData: [testData.creatureMoveEvent],
		lookupFields: [
			{
				fieldName: 'world_id',
				newFieldName: 'world_id',
				table: 'worlds',
				externalIdField: 'fv_world_id',
				internalIdField: 'world_id',
				requiresWorldId: false,
			},
			{
				fieldName: 'creature_id',
				newFieldName: 'creature_id',
				table: 'creatures',
				externalIdField: 'fv_creature_id',
				internalIdField: 'creature_id',
				requiresWorldId: false,
			},
			{
				fieldName: 'game_time_id',
				newFieldName: 'game_time_id',
				table: 'game_times',
				externalIdField: 'fv_game_time_id',
				internalIdField: 'game_time_id',
				requiresWorldId: false,
			},
			{
				fieldName: 'location_id',
				newFieldName: 'area_id',
				table: 'areas',
				externalIdField: 'fv_area_id',
				internalIdField: 'area_id',
				requiresWorldId: false,
			},
		],
	},
	'creature-activity-events': {
		externalUrl: `${EXTERNAL_URL}creature-activity-events/`,
		schema: schemas.creatureActivityEventSchema,
		newTypes: ['creature-activity-records'],
		testData: [testData.creatureActivityEvent],
		lookupFields: [
			{
				fieldName: 'world_id',
				newFieldName: 'world_id',
				table: 'worlds',
				externalIdField: 'fv_world_id',
				internalIdField: 'world_id',
				requiresWorldId: false,
			},
			{
				fieldName: 'creature_id',
				newFieldName: 'creature_id',
				table: 'creatures',
				externalIdField: 'fv_creature_id',
				internalIdField: 'creature_id',
				requiresWorldId: false,
			},
			{
				fieldName: 'game_time_id',
				newFieldName: 'game_time_id',
				table: 'game_times',
				externalIdField: 'fv_game_time_id',
				internalIdField: 'game_time_id',
				requiresWorldId: false,
			},
			{
				fieldName: 'location_id',
				newFieldName: 'area_id',
				table: 'areas',
				externalIdField: 'fv_area_id',
				internalIdField: 'area_id',
				requiresWorldId: false,
			},
			{
				fieldName: 'activity_event_type',
				newFieldName: 'activity_type_id',
				table: 'activity_types',
				externalIdField: 'fv_activity_type_id',
				internalIdField: 'activity_type_id',
				requiresWorldId: false,
			},
		],
	},
	'diner-rating-events': {
		externalUrl: `${EXTERNAL_URL}diner-rating-events/`,
		schema: schemas.dinerRatingEventSchema,
		newTypes: ['diner-review-actions'],
		testData: [testData.dinerRatingEvent],
		lookupFields: [
			{
				fieldName: 'world_id',
				newFieldName: 'world_id',
				table: 'worlds',
				externalIdField: 'fv_world_id',
				internalIdField: 'world_id',
				requiresWorldId: false,
			},
			{
				fieldName: 'creature_id',
				newFieldName: 'creature_id',
				table: 'creatures',
				externalIdField: 'fv_creature_id',
				internalIdField: 'creature_id',
				requiresWorldId: false,
			},
			{
				fieldName: 'game_time_id',
				newFieldName: 'game_time_id',
				table: 'game_times',
				externalIdField: 'fv_game_time_id',
				internalIdField: 'game_time_id',
				requiresWorldId: false,
			},
			{
				fieldName: 'item_id',
				newFieldName: 'item_id',
				table: 'items',
				externalIdField: 'fv_item_id',
				internalIdField: 'item_id',
				requiresWorldId: true,
			},
		],
	},
	'diner-seating-events': {
		externalUrl: `${EXTERNAL_URL}diner-seating-events/`,
		schema: schemas.dinerSeatingEventSchema,
		newTypes: ['diner-seating-actions'],
		testData: [testData.dinerSeatingEvent],
		lookupFields: [
			{
				fieldName: 'world_id',
				newFieldName: 'world_id',
				table: 'worlds',
				externalIdField: 'fv_world_id',
				internalIdField: 'world_id',
				requiresWorldId: false,
			},
			{
				fieldName: 'player_id',
				newFieldName: 'player_id',
				table: 'players',
				externalIdField: 'fv_player_id',
				internalIdField: 'player_id',
				requiresWorldId: false,
			},
			{
				fieldName: 'creature_id',
				newFieldName: 'creature_id',
				table: 'creatures',
				externalIdField: 'fv_creature_id',
				internalIdField: 'creature_id',
				requiresWorldId: false,
			},
			{
				fieldName: 'game_time_id',
				newFieldName: 'game_time_id',
				table: 'game_times',
				externalIdField: 'fv_game_time_id',
				internalIdField: 'game_time_id',
				requiresWorldId: false,
			},
		],
	},
	'player-manipulate-data-events': {
		externalUrl: `${EXTERNAL_URL}player-manipulate-data-events/`,
		schema: schemas.playerManipulateDataEventSchema,
		newTypes: ['data-actions', 'data-tables'],
		testData: [
			testData.playerManipulateDataEvent,
			testData.playerManipulateDataEvent,
		],
		lookupFields: [
			{
				fieldName: 'world_id',
				newFieldName: 'world_id',
				table: 'worlds',
				externalIdField: 'fv_world_id',
				internalIdField: 'world_id',
				requiresWorldId: false,
			},
			{
				fieldName: 'player_id',
				newFieldName: 'player_id',
				table: 'players',
				externalIdField: 'fv_player_id',
				internalIdField: 'player_id',
				requiresWorldId: false,
			},
			{
				fieldName: 'game_time_id',
				newFieldName: 'game_time_id',
				table: 'game_times',
				externalIdField: 'fv_game_time_id',
				internalIdField: 'game_time_id',
				requiresWorldId: false,
			},
			{
				fieldName: 'table_id',
				newFieldName: 'data_table_id',
				table: 'data_tables',
				externalIdField: 'fv_data_table_id',
				internalIdField: 'data_table_id',
				requiresWorldId: false,
			},
			{
				fieldName: 'table_being_merged_id',
				newFieldName: 'data_table_id',
				table: 'data_tables',
				externalIdField: 'fv_data_table_id',
				internalIdField: 'data_table_id',
				requiresWorldId: false,
			},
		],
	},
	'player-move-events': {
		externalUrl: `${EXTERNAL_URL}player-move-events/`,
		schema: schemas.playerMoveEventSchema,
		newTypes: ['player-location-records'],
		testData: [testData.playerMoveEvent],
		lookupFields: [
			{
				fieldName: 'world_id',
				newFieldName: 'world_id',
				table: 'worlds',
				externalIdField: 'fv_world_id',
				internalIdField: 'world_id',
				requiresWorldId: false,
			},
			{
				fieldName: 'player_id',
				newFieldName: 'player_id',
				table: 'players',
				externalIdField: 'fv_player_id',
				internalIdField: 'player_id',
				requiresWorldId: false,
			},
			{
				fieldName: 'game_time_id',
				newFieldName: 'game_time_id',
				table: 'game_times',
				externalIdField: 'fv_game_time_id',
				internalIdField: 'game_time_id',
				requiresWorldId: false,
			},
			{
				fieldName: 'location_id',
				newFieldName: 'area_id',
				table: 'areas',
				externalIdField: 'fv_area_id',
				internalIdField: 'area_id',
				requiresWorldId: false,
			},
		],
	},
	'player-item-interaction-events': {
		externalUrl: `${EXTERNAL_URL}player-item-interaction-events/`,
		schema: schemas.playerItemInteractionEventSchema,
		newTypes: ['inventory-actions'],
		testData: [testData.playerItemInteractionEvent],
		lookupFields: [
			{
				fieldName: 'game_time_id',
				newFieldName: 'game_time_id',
				table: 'game_times',
				externalIdField: 'fv_game_time_id',
				internalIdField: 'game_time_id',
				requiresWorldId: false,
			},
			{
				fieldName: 'world_id',
				newFieldName: 'world_id',
				table: 'worlds',
				externalIdField: 'fv_world_id',
				internalIdField: 'world_id',
				requiresWorldId: false,
			},
			{
				fieldName: 'player_id',
				newFieldName: 'player_id',
				table: 'players',
				externalIdField: 'fv_player_id',
				internalIdField: 'player_id',
				requiresWorldId: false,
			},
			{
				fieldName: 'item_id',
				newFieldName: 'item_id',
				table: 'items',
				externalIdField: 'fv_item_id',
				internalIdField: 'item_id',
				requiresWorldId: true,
			},
			{
				fieldName: 'item_id',
				newFieldName: 'resource_id',
				table: 'resources',
				externalIdField: 'fv_resource_id',
				internalIdField: 'resource_id',
				requiresWorldId: true,
			},
			{
				fieldName: 'inventory',
				newFieldName: 'inventory_id',
				table: 'inventories',
				externalIdField: 'fv_inventory_id',
				internalIdField: 'inventory_id',
				requiresWorldId: false,
			},
		],
	},
	'direct-creature-events': {
		externalUrl: `${EXTERNAL_URL}direct-creature-events/`,
		schema: schemas.directCreatureEventSchema,
		newTypes: ['creature-direction-actions'],
		testData: [testData.directCreatureEvent],
		lookupFields: [
			{
				fieldName: 'world_id',
				newFieldName: 'world_id',
				table: 'worlds',
				externalIdField: 'fv_world_id',
				internalIdField: 'world_id',
				requiresWorldId: false,
			},
			{
				fieldName: 'game_time_id',
				newFieldName: 'game_time_id',
				table: 'game_times',
				externalIdField: 'fv_game_time_id',
				internalIdField: 'game_time_id',
				requiresWorldId: false,
			},
			{
				fieldName: 'player_id',
				newFieldName: 'player_id',
				table: 'players',
				externalIdField: 'fv_player_id',
				internalIdField: 'player_id',
				requiresWorldId: false,
			},
			{
				fieldName: 'creature_id',
				newFieldName: 'creature_id',
				table: 'creatures',
				externalIdField: 'fv_creature_id',
				internalIdField: 'creature_id',
				requiresWorldId: false,
			},
			{
				fieldName: 'from_location_id',
				newFieldName: 'area_id',
				table: 'areas',
				externalIdField: 'fv_area_id',
				internalIdField: 'area_id',
				requiresWorldId: false,
			},
			{
				fieldName: 'to_location_id',
				newFieldName: 'area_id',
				table: 'areas',
				externalIdField: 'fv_area_id',
				internalIdField: 'area_id',
				requiresWorldId: false,
			},
		],
	},
	'anomaly-readings': {
		externalUrl: `${EXTERNAL_URL}anomaly-readings/`,
		schema: schemas.anomalyReadingSchema,
		newTypes: ['anomaly-readings'],
		testData: [testData.anomalyReading],
		lookupFields: [
			{
				fieldName: 'world_id',
				newFieldName: 'world_id',
				table: 'worlds',
				externalIdField: 'fv_world_id',
				internalIdField: 'world_id',
				requiresWorldId: false,
			},
			{
				fieldName: 'game_time_id',
				newFieldName: 'game_time_id',
				table: 'game_times',
				externalIdField: 'fv_game_time_id',
				internalIdField: 'game_time_id',
				requiresWorldId: false,
			},
			{
				fieldName: 'player_id',
				newFieldName: 'player_id',
				table: 'players',
				externalIdField: 'fv_player_id',
				internalIdField: 'player_id',
				requiresWorldId: false,
			},
		],
	},
	'request-board-actions': {
		externalUrl: `${EXTERNAL_URL}request-board-actions/`,
		schema: schemas.requestBoardActionSchema,
		newTypes: ['request-board-actions'],
		testData: [testData.requestBoardAction],
		lookupFields: [
			{
				fieldName: 'world_id',
				newFieldName: 'world_id',
				table: 'worlds',
				externalIdField: 'fv_world_id',
				internalIdField: 'world_id',
				requiresWorldId: false,
			},
			{
				fieldName: 'player_id',
				newFieldName: 'player_id',
				table: 'players',
				externalIdField: 'fv_player_id',
				internalIdField: 'player_id',
				requiresWorldId: false,
			},
			{
				fieldName: 'creature_id',
				newFieldName: 'creature_id',
				table: 'creatures',
				externalIdField: 'fv_creature_id',
				internalIdField: 'creature_id',
				requiresWorldId: false,
			},
			{
				fieldName: 'item_id',
				newFieldName: 'item_id',
				table: 'items',
				externalIdField: 'fv_item_id',
				internalIdField: 'item_id',
				requiresWorldId: true,
			},
			{
				fieldName: 'game_time_id',
				newFieldName: 'game_time_id',
				table: 'game_times',
				externalIdField: 'fv_game_time_id',
				internalIdField: 'game_time_id',
				requiresWorldId: false,
			},
			{
				fieldName: 'request_board_item_id',
				newFieldName: 'request_board_item_id',
				table: 'request_board_items',
				externalIdField: 'fv_request_board_item_id',
				internalIdField: 'request_board_item_id',
				requiresWorldId: false,
			},
		],
	},
	'imbalance-records': {
		externalUrl: `${EXTERNAL_URL}imbalance-records/`,
		schema: schemas.imbalanceRecordSchema,
		newTypes: ['imbalance-records'],
		testData: [testData.imbalanceRecord],
		lookupFields: [
			{
				fieldName: 'world_id',
				newFieldName: 'world_id',
				table: 'worlds',
				externalIdField: 'fv_world_id',
				internalIdField: 'world_id',
				requiresWorldId: false,
			},
			{
				fieldName: 'game_time_id',
				newFieldName: 'game_time_id',
				table: 'game_times',
				externalIdField: 'fv_game_time_id',
				internalIdField: 'game_time_id',
				requiresWorldId: false,
			},
		],
	},
};

const oldUnusedDataTypes = {
	'simulation-stats': {
		externalUrl: `${EXTERNAL_URL}simulation-stats/`,
		schema: schemas.simulationStatsSchema,
		newTypes: ['simulation-stats'],
	},
	'item-attribute-1s': {
		externalUrl: `${EXTERNAL_URL}item-attribute-1s/`,
		schema: schemas.itemAttribute1Schema,
		newTypes: ['item-attributes'],
	},
	'item-attribute-2s': {
		externalUrl: `${EXTERNAL_URL}item-attribute-2s/`,
		schema: schemas.itemAttribute2Schema,
		newTypes: ['item-attributes'],
	},
	'sheet-links': {
		externalUrl: `${EXTERNAL_URL}sheet-links/`,
		schema: schemas.sheetLinkSchema,
		newTypes: ['sheet-links'],
	},
};

export default oldEventDataTypes;
