export default {
    "islands": [
        { island_id: 1, island_name: 'Shadow Island' },
        { island_id: 2, island_name: 'Light Island' },
        { island_id: 3, island_name: 'Growth Island' },
        { island_id: 4, island_name: 'Stability Island' },
    ],
    "inventories": [
        { inventory_id: 'Icebox', inventory_name: 'Icebox' },
        { inventory_id: 'Ready To Serve', inventory_name: 'Ready To Serve' },
        { inventory_id: 'Shared Inventory', inventory_name: 'Shared Inventory' },
        { inventory_id: 'Workshop Chest', inventory_name: 'Workshop Chest' },
    ],
    "activity-types": [
        { activity_type_id: 0, activity_type_name: 'None' },
        { activity_type_id: 1, activity_type_name: 'Music' },
        { activity_type_id: 2, activity_type_name: 'Craft' },
        { activity_type_id: 3, activity_type_name: 'Writing' },
        { activity_type_id: 4, activity_type_name: 'Textiles' },
    ],
    "item-categories": [
        { item_category_id: 2, item_category_name: 'Health Potion' },
        { item_category_id: 4, item_category_name: 'Food' },
        { item_category_id: 8, item_category_name: 'Gift' },
        { item_category_id: 16, item_category_name: 'Patch Crystal' }
    ],
    "item-varieties": [
        { item_variety_id: 1, item_variety_name: 'Smoothie', item_category_id: 4 },
        { item_variety_id: 2, item_variety_name: 'Jelly', item_category_id: 4 },
        { item_variety_id: 3, item_variety_name: 'Pastry', item_category_id: 4 },
        { item_variety_id: 4, item_variety_name: 'Cupcake', item_category_id: 4 },
        { item_variety_id: 5, item_variety_name: 'Rejuvenation Tea', item_category_id: 2 },
        { item_variety_id: 6, item_variety_name: 'Protection Tonic', item_category_id: 2 },
        { item_variety_id: 7, item_variety_name: 'Enchantment Brew', item_category_id: 2 },
        { item_variety_id: 8, item_variety_name: 'Luminous Boba', item_category_id: 2 },
        { item_variety_id: 9, item_variety_name: 'Harmonics', item_category_id: 8 },
        { item_variety_id: 10, item_variety_name: 'Masonry', item_category_id: 8 },
        { item_variety_id: 11, item_variety_name: 'Secretspinning', item_category_id: 8 },
        { item_variety_id: 12, item_variety_name: 'Fibercraft', item_category_id: 8 },
        { item_variety_id: 13, item_variety_name: 'Growth', item_category_id: 16 },
        { item_variety_id: 14, item_variety_name: 'Stability', item_category_id: 16 },
        { item_variety_id: 15, item_variety_name: 'Shadow', item_category_id: 16 },
        { item_variety_id: 16, item_variety_name: 'Light', item_category_id: 16 },
    ],
};